language: go
env: GO111MODULE=on
go:
  - 1.11.4
  - 1.12
  - 1.13
  - 1.14
before_install:
  - go get -v ./...
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
