language: go
env: GO111MODULE=on
go:
  - 1.11.4
  - 1.12.x
  - 1.13.x
  - tip
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
matrix:
  allow_failures:
    - go: tip
